### ISSUE TITLE
Hide footers on Parker exhibit

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/exhibits#529] opened 2017-08-11 18:26 UTC
In trying to minimize the amount of Stanford branding on the Parker product, it is desirable to hide the heavy Stanford branding in the two footers (Stanford Libraries and Stanford University).

**Comment by ggeisler** [comment] 2017-08-11 18:55
Duplicate of #527

**Closed** 2017-08-11 18:55 UTC
Labels: parker
