### ISSUE TITLE
BL7: Navigation at the bottom of the Exhibits home page looks wonky for page 1

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1721] opened 2020-02-20 18:21 UTC
Can we suppress the empty bullet (navigation related) on the bottom of the home page?

<img width="863" alt="Screen Shot 2020-02-20 at 10 20 12 AM" src="https://user-images.githubusercontent.com/3210225/74965746-a2ea8880-53ca-11ea-8c50-e23f714ace69.png">

**Comment by mejackreed** [comment] 2020-02-20 18:32
A duplicate of https://github.com/sul-dlss/exhibits/issues/1707 will be resolved when Exhibits is updated in Spotlight.

**Closed** 2020-02-20 18:58 UTC
