### ISSUE TITLE
Uploaded item image (non-SDR item) is not rendered in exhibit

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#1909] opened 2020-08-06 00:24 UTC
Using this exhibit as a test case: https://exhibits.stanford.edu/test-stn/catalog/admin?sort=timestamp

1. I uploaded an item using the Curation > Items > Add items > Upload item form

2. Item is added successfully, in that it is shown in the Items list.

3. The item thumbnail, however, is **not** displayed in the Items list.

4. When navigating to the item show page ( https://exhibits.stanford.edu/test-stn/catalog/215-69504), the image uploaded with the item doesn't display in the viewer. I tried both Chrome and Safari with same result; neither browser is showing any console errors when loading the page.

<img width="525" alt="Screen Shot 2020-08-05 at 5 21 19 PM" src="https://user-images.githubusercontent.com/101482/89476635-19443280-d740-11ea-8f3b-de66b31b02e3.png">

I've tried this in a couple of test exhibits with the same result. The exhibit above was created in the past couple of weeks.

**Comment by cbeer** [comment] 2020-08-06 00:57
99% sure this is a duplicate of #1903.

**Closed by cbeer** 2020-08-06 00:57 UTC
Labels: bug

**Comment by ggeisler** [comment] 2020-08-06 00:59
Yes, definitely, I forgot about that one.
