### ISSUE TITLE
Analysis needed: IIIF images in exhibit - pagination & zoom controls not working consistently

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1290] opened 2018-11-29 17:16 UTC
Curator Regan Murphy Kao is trying to create the following exhibit & populate it with some IIIF content from various institutions: https://exhibits.stanford.edu/henro. Regan is currently blocked for further work on this exhibit, due to the problems with navigation and display of IIIF resources in her unpublished exhibit.

In an email conversation with Regan, me & Stu -- Stu confirmed the behavior that Regan reported:

"Changing the viewer to Mirador does not resolve it, alas.  Currently external IIIF resources are viewed in a vanilla version of OpenSeadragon.  The preferred behavior would be for external IIIF resources to be viewable in one of the two IIIF-compatible viewers we have in spotlight.  I’ve submitted this as an issue.

But even with the OSD viewer, I can confirm that the pagination and zoom controls are not working consistently.  This is a bug."

Please see the two tickets that Stu created: #1216 & #1217.

This may be helpful additional information, provided by Regan:

Here is a list of organizations (and example images) where the images for the exhibit would be coming from.

National Institute for Japanese Literature:
for example:
http://www2.dhii.jp/nijl/kanzo/iiif/200010482/manifest.json
and:
https://kotenseki.nijl.ac.jp/biblio/200000880/viewer

National Diet Library:
for example:
https://www.dl.ndl.go.jp/api/iiif/904125/manifest.json

Possibly:
Kyoto University Library
https://rmda.kulib.kyoto-u.ac.jp/en
for example:
https://rmda.kulib.kyoto-u.ac.jp/iiif/metadata_manifest/RB00020075/manifest.json

Keio University Library:
for example:
http://dcollections.lib.keio.ac.jp/ja/icp/132x-26-1

SAT Taishozo Image Database:
https://dzkimgs.l.u-tokyo.ac.jp/SATi/images.php
for example:
https://dzkimgs.l.u-tokyo.ac.jp/iiif/zuzoubu/12b02/manifest.json

Last but not least, here is an email exchange between Camille & Cathy containing some preliminary analysis:

From: Catherine A. Aster
Sent: Thursday, August 9, 2018 3:02 PM
To: Camille Villa; Stuart Snydman; Benjamin L Albritton; Gary Geisler
Cc: dlss-access-team@lists.stanford.edu
Subject: Re: External IIIF manifests in Exhibits
 
Hi Camille,

Thank you for your excellent analysis and summary of the issues.

The exhibit creators I am aware of who are wanting to create an exhibit where they are importing IIIF resources (or are currently doing/have done so):

Regan Murphy-Kao - https://exhibits.stanford.edu/henro

Amy Hodge, as you are aware (future exhibit)

Ben Albritton - https://exhibits.stanford.edu/parker

Ben Albritton, when he works with his students - https://exhibits.stanford.edu/mss

I also anticipate expanded future use of IIIF resources in exhibits, if we can get it all working acceptably & sustainably.

I want to make sure we get a good group to come together and discuss this, to make the right set of policy decisions. This should definitely include Ben, Stu & me, among others. Of course, I am particularly interested in the service implications for exhibits.

Hopefully when Stu returns we can caucus on the issues?

Best,
Cathy

Cathy Aster
Services Manager
Spotlight at Stanford
Electronic Theses & Dissertations
Liaison to DRMC for Map Projects
https://library.stanford.edu/people/caster
Digital Library Systems & Services
Stanford Libraries
mobile: 650.619.3930
________________________
From: Camille Villa <cvilla@stanford.edu>
Sent: Thursday, August 9, 2018 11:21 AM
To: Stuart Snydman; Catherine A. Aster; Benjamin L Albritton; Gary Geisler
Cc: dlss-access-team@lists.stanford.edu
Subject: External IIIF manifests in Exhibits
 
Hi all,

Here’s what I’ve dug up from looking into the OSD bug and potentially replacing it with Mirador for external IIIF.

Good news:

- Zoom controls are still working in OSD, they just (continue to be) miserable. See click offsets in exhibits#1217.

- I have a work-in-progress PR that successfully uses Mirador for displaying *some* external IIIF resources (exhibits#1227).

Bad news:

Shipping this now would introduce some headaches on the service side. Currently, Spotlight does not offer great validation for external manifests. I've been gathering data on manifests by institution and external manifests do not behave consistently. Some invalid manifests will successfully import, while some valid manifests fail to import.

Things needed to move this feature forward:

(a) a policy decision re: whether we should support invalid manifests at all, providing training for curators on using  IIIF validators, could they contribute to the spreadsheet etc.

(b) scheduling time for more detailed study of validation reports and developing more robust error handling either upstream in Spotlight or locally in Exhibits

(c) a better understanding of our current landscape of external IIIF usage. For example: how many curators are currently using external IIIF in their exhibits? How many have attempted to use this feature and given up? What institutions are curators trying to use manifests from?

(d) will switching to Mirador cause a regression for any *current* exhibits? Switching now would have an impact on future projects (e.g. Amy Hodge hoped to build an exhibit with LOC manifests soon). These manifests display in OSD but do not render in Mirador. This specific case could possibly be resolved by spotlight#2089. Jack has reached out to LOC about their manifests in the mean time).

Any contributions to this external IIIF manifest spreadsheet would be greatly appreciated:

https://docs.google.com/spreadsheets/d/1WHskmgTfZkREYIYOKI7cONo04YZ-VIKfBBMFhwjaWMI/edit#gid=930478489

Cheers,
Camille
-- 
Camille Villa
Digital Library Research Engineer
Stanford University Libraries

**Comment by camillevilla** [comment] 2018-11-29 18:57
@caaster I believe this is a duplicate of #1217, where I also worked with an item from Regan's exhibit. The zoom and pagination controls in OSD are functional, but very poor. That is not an issue that we will be able to fix any time soon. 

I think moving this issue forward will build on the work I did in #1227.

**Comment by camillevilla** [comment] 2018-11-29 18:58
(Getting the email conversation and the analysis there into GitHub is definitely helpful, however!)

**Comment by caaster** [comment] 2018-11-29 19:18
@camillevilla do you recommend I close this ticket, then? happy to do whatever you think best.

and wondering, since #1227 is almost ready, is there any need to place it on my board? https://github.com/sul-dlss/exhibits/projects/4

**Comment by camillevilla** [comment] 2018-11-29 20:08
@caaster Let's close this for now. And I think we should probably close #1217 as well, since it isn't really actionable.

I've update #1227 with more info about remaining dev work + analysis. And yes, let's place it on your board. I've also added it to the Access Team board as well.

**Closed** 2018-11-29 21:13 UTC
Labels: Needs Analysis, blocked
