### ISSUE TITLE
IIIF manifest upload is not working; library system status page displays when upload is attempted

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1922] opened 2020-08-26 18:51 UTC
**Desired fix timeline: NLT 23 September 2020**

I could use some help with this IIIF-Spotlight query from Andrea Renner. She is attempting to upload some IIIF manifest URLs to a Spotlight exhibit and not having any luck. I asked her to send me an example which she has done, below. When I attempt to upload this URL to a test exhibit, I can verify that I get the System Status page as well, as Andrea has stated.

https://www.davidrumsey.com/luna/servlet/iiif/m/RUMSEY~8~1~321912~90091033/manifest

It's this item: https://www.davidrumsey.com/luna/servlet/s/k6eyxt

**Context related to desired fix timeline**

1) The [Data Visualization and Modern Imagination](https://exhibits.stanford.edu/dataviz) exhibit will be published in concurrence with a DRMC virtual conference scheduled for 25 Sept 2020. 300 people have signed up to attend the conference so far. The Rumsey maps that the DRMC wants to upload to this exhibit are from David's collection, but they are not in the SDR yet. Showcasing these maps in the exhibit using the IIIF manifest import is the preferred option.

2) The [National History Day, Maps Edition](https://exhibits.stanford.edu/nhdmaps) exhibit will be published by the end of September 2020. It is in support of a global event called "National History Day," in which 600,000 high school students will participate. Many of these students will be able to visit Stanford's National History Day exhibit and use the resources they find there to create their map projects, akin to how students create science projects for National Science Day. The DRMC wants to upload many Rumsey maps that are not yet in the SDR for this exhibit -- including all of the maps that will be used to populate a section on "Slavery in America."

**Comment by anarchivist** [comment] 2020-09-02 17:16
Documenting here, just for reference. This was initially caused by the [SSL certificate chain issue](https://calnetweb.berkeley.edu/calnet-technologists/incommon-sectigo-certificate-service/addtrust-external-root-expiration-may-2020) we ran into back in May. We had David and Drake follow up and reissue a new SSL certificate. 

This seems to have uncovered another issue, which is that davidrumsey.com does not return the expected MIME type for IIIF manifests upon HTTP `HEAD` requests. This means that currently, our "preflight" check of the manifest fails. We'd contacted Drake about this issue in September 2019 as well. I think it'd be preferable if this is fixed on the Luna end, but we can implement a workaround if needed.

**Comment by caaster** [comment] 2020-09-02 17:24
I will reach out to Andrea and David with this additional information.

**Comment by anarchivist** [comment] 2020-09-04 20:13
This has been fixed on the davidrumsey.com side of things, as confirmed by @caaster.

**Closed by anarchivist** 2020-09-04 20:13 UTC
Labels: bug
