### ISSUE TITLE
[exhibits/prod] ActionView::Template::Error: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/exhibits#789] opened 2017-10-23 15:58 UTC
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49092/faults/35145381)

**Comment by camillevilla** [comment] 2017-10-23 16:44
So this bug is getting thrown by a `sir_trevor_rails` override in projectblacklight/spotlight
```ruby
def as_json
  result = super
    result[:data][:item].each do |_k, v|
      v['thumbnail_image_url'] = parent.exhibit.searches.find(v['id']).thumbnail_image_url
    end
  result
end
```
 ([source](https://github.com/projectblacklight/spotlight/blob/f5c3e65b204fd0f30fab4539d99273507ded3ab3/app/models/sir_trevor_rails/blocks/browse_block.rb#L35))

**Comment by camillevilla** [comment] 2017-10-23 16:50
I've found some fishy things by poking around the Alcoa exhibit in prod. 

## Data leaking into the about pages / sir trevor interface is gone
This bug isn't reproducible 100% of the time, but seems to pop up after I try to edit the home page. 

<img width="984" alt="curation_-_edit_page___alcoa__research_and_context_-_spotlight_at_stanford_and_dlss" src="https://user-images.githubusercontent.com/5402927/31901621-cf2f0700-b7d6-11e7-9698-c159de7bcee2.png">

## Existing data is not available for editing

<img width="981" alt="curation_-_edit_page___alcoa__research_and_context_-_spotlight_at_stanford" src="https://user-images.githubusercontent.com/5402927/31901811-7078eda6-b7d7-11e7-8939-34fdfff9f115.png">

**Comment by camillevilla** [comment] 2017-10-23 17:58
It looks like something similar has happened before:
[projectblacklight/spotlight #1774](https://github.com/projectblacklight/spotlight/issues/1774)
@jkeck mentions fixing data manually...

And it looks like this sir_trevor bug is still open on [projectblacklight/spotlight #1782](https://github.com/projectblacklight/spotlight/issues/1782)

**Comment by camillevilla** [comment] 2017-10-23 21:08
<img width="942" alt="screen shot 2017-10-23 at 2 05 30 pm" src="https://user-images.githubusercontent.com/5402927/31913272-94c77078-b7fb-11e7-9455-5acf758e2823.png">

**Comment by camillevilla** [comment] 2017-10-24 18:59
Update: should be resolved by upstream changes to Spotlight
see: projectblacklight/spotlight#1850

**Closed** 2017-10-25 20:16 UTC
Labels: bug, production, ready
