### ISSUE TITLE
Load from IIIF URL not working

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1413] opened 2019-08-12 17:58 UTC
Load from IIIF URL does not appear to be working. See this page, loaded from https://digi.vatlib.it/iiif/MSS_Urb.lat.274/manifest.json, for: https://exhibits.stanford.edu/leonardo

**Comment by cbeer** [comment] 2019-08-12 18:04
Can you be more specific? It seems like it was added into exhibits just fine (https://exhibits.stanford.edu/leonardo/catalog/a25aa69f358ea6028494ecd0b6cf9fdc ), but openseadragon certainly struggles to display it.

**Comment by caaster** [comment] 2019-08-12 18:07
@blalbrit - since you reported this issue, I am reaching out to see if you are able to add amplifying information. Thanks in advance.

**Comment by blalbrit** [comment] 2019-08-12 18:14
Yes - as @cbeer notes, the item was added to the exhibit, but openseadragon fails to display it. Successfully loading an object that cannot be rendered.

See the page I reported from: https://exhibits.stanford.edu/leonardo/catalog/a25aa69f358ea6028494ecd0b6cf9fdc

Let me know if there's anything unclear about that.

**Comment by cbeer** [comment] 2019-08-12 18:22
Ok. I'd probably call this a duplicate of https://github.com/sul-dlss/exhibits/issues/1216 then? I don't see us doing anything but replacing OSD entirely.

**Comment by blalbrit** [comment] 2019-08-12 18:27
Makes sense - didn't realize this was already a known problem.

@caaster and @cbeer - am I correct that switching to Mirador for the exhibit has no effect? I tried it, and there was no actual change in viewer for that item - but maybe there's a more complicated recipe than just "change default viewer" to have a work around?

**Comment by caaster** [comment] 2019-08-12 19:25
@blalbrit the change default viewer to Mirador option only works for image content in the SDR. That's how it was configured, yet I see that we did not document this important nuance: https://exhibits.stanford.edu/exhibits-documentation/feature/viewers. I'm adding it to our change log that we use to maintain the Exhibits Documentation exhibit, so it will be added.

**Comment by caaster** [comment] 2019-08-12 19:45
@blalbrit @cbeer We also need to suppress this option from being available in exhibits if it doesn't work. At least until we come up with a solution that does work. I will create a ticket.

**Comment by camillevilla** [comment] 2019-08-13 18:53
@caaster we are working on replacing the dreadful OSD with Mirador 3 in exhibits (at last!) in #1415. Work there has been deployed to stage. We'd like to work with PSM on QA'ing this approach and hopefully unlock a better user experience for external IIIF.

**Comment by caaster** [comment] 2019-08-13 18:55
@camillevilla Excellent news! Can we chat in person about the PSM QA?

**Closed** 2019-11-18 22:31 UTC
