### ISSUE TITLE
Aspect ratio for contact thumbnail photos makes people appear ghoulish

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1851] opened 2020-03-24 15:27 UTC
Here is an example of the problem (https://exhibits.stanford.edu/fitch/about/the-bob-fitch-photography-archive-at-stanford). Please note, this is not unique to this exhibit:

![Screen Shot 2020-03-24 at 8 25 45 AM](https://user-images.githubusercontent.com/3210225/77444466-1b1ce300-6da9-11ea-8153-7bfa8bb582c2.png)

**Comment by anarchivist** [comment] 2020-03-24 15:46
duplicate of #1848

**Closed** 2020-03-24 19:14 UTC
Labels: bug
