### ISSUE TITLE
Date range slider not appearing on home page

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#1356] opened 2019-05-01 16:22 UTC
Reported for the unpublished radar films exhibit and seen on Virtual Tribunals in prod exhibits. The date range facet that appears **on the home page** does not display the date slider. However, if you start from a search context, it appears.

_From the home page_

![daterange](https://user-images.githubusercontent.com/73732/57027785-2ba4f780-6bf2-11e9-9613-ef323f4f5493.gif)

_From a search context (empty query)_

![directory](https://user-images.githubusercontent.com/73732/57027930-8fc7bb80-6bf2-11e9-9109-8ec8e29c9d56.gif)

**Comment by cbeer** [comment] 2019-05-01 17:47
Duplicate of https://github.com/sul-dlss/exhibits/issues/1010 (marked fixed, although maybe that's just because no action was an acceptable resolution). Getting facets on the home page is still 3-5 days of effort.

**Closed** 2020-01-16 20:10 UTC
Labels: Exhibits Pri 1, bug
