### ISSUE TITLE
Prod: Skip link not hidden on search result page

### ISSUE THREAD

**Issue by alundgard** [sul-dlss/exhibits#2759] opened 2024-12-18 14:28 UTC
The `Skip to first result` skip link appears to display constantly (without receiving keyboard focus) on the search result pages.

https://exhibits.stanford.edu/regina-gelana-twala/catalog?exhibit_id=regina-gelana-twala&search_field=search&q=
<img width="1496" alt="Image" src="https://github.com/user-attachments/assets/fd778fe1-c464-4771-8765-34014c369497" />

https://exhibits.stanford.edu/martin-wong/catalog?exhibit_id=martin-wong&search_field=search&q=
<img width="1497" alt="Image" src="https://github.com/user-attachments/assets/dfdbadf0-af94-4506-a851-14c528d0f13c" />

**Comment by jcoyne** [comment] 2024-12-18 14:29
Duplicate of #2756

**Closed by jcoyne** 2024-12-18 14:29 UTC
Labels: bug, production
