### ISSUE TITLE
Add annotation handling (...indexing) into the re-indexing job.

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/exhibits#756] opened 2017-10-18 18:06 UTC
Acceptance criteria:

- [ ] Annotation indexing/reindex should be part of main `ReindexJob` for an SDR object
- [ ] Note that it's featured flags for the Parker exhibit only (#757)

Story #714 
Analysis #728 
Fixtures #729

**Comment by mejackreed** [comment] 2017-10-31 17:48
Feeling like a duplicate of #805

**Closed by mejackreed** 2017-10-31 17:48 UTC
Labels: annotations, parker
