### ISSUE TITLE
Unpublished Alcoa exhibit has disappeared & exhibit creator is having problems

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#788] opened 2017-10-22 20:35 UTC
Exhibit creator just filed the following feedback report:

From: "Erika Tribett" <etribett@stanford.edu>

I am unable to create new About and Feature pages. When I attempt to name a page and save it, I receive an error stating, "We're sorry but something went wrong. If you are the owner check the logs for more information."

----
REMOTE_IP
73.162.91.26
USER AGENT
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
EXHIBIT
Alcoa: Research and Context
CURRENT_URL
https://exhibits.stanford.edu/alcoa/about
UUID
2bb8c1fd-48ba-443c-90e2-42a38f36534f

***********

To validate the user reported problem, I first navigated to the unpublished exhibits tab on exhibits.stanford.edu. **The Alcoa exhibit is missing!** However, when I navigate directly to: https://exhibits.stanford.edu/alcoa/about -- I see the exhibit, go to the dashboard, and I am able to create new test feature & about pages (which I then deleted).

What has happened to the Alcoa exhibit? It is unpublished & in the process of being populated. I created the Alcoa exhibit stub on 6 Oct 2017.

**Comment by blalbrit** [comment] 2017-10-23 15:36
Hi @caaster 

Based on your slack msg, you would like me to look at this today. However, it looks like from the thread copied below that the user uncovered at least part of the problem (names were too long for specific pages). I know you're conferencing this week, but when you have time could you please update this ticket with more specifics?

It seems like the ticket addresses several distinct symptoms:

- https://exhibits.stanford.edu/alcoa has disappeared from the exhibits.stanford.edu homepage
- user was having trouble saving specific pages, but that seems to be solved [?]
- user is having difficulty editing pages: "Hello - I am unable to edit About pages. When I attempt to add a component via the + sign, it shows me an "x" with no options for any widgets. I am trying to create a People page with thumbnail photos on the left and text on the right. I am also trying to create a timeline of our research. Please let me know if you have any suggestions. Erika" This was reported this morning, but I can not reproduce it - I have no problem editing the Alcoa About page. Is it possible this user simply requires more training and/or an investigation into the browser/OS combo they are using?

B.

___
Hello,

Thank you for the prompt reply, Cathy. I think it may have to do with the length of the page name. I created a new page "People" and it worked just fine, so I went back and renamed the initial page I was trying to create.

I'll let you know if this happens in any other circumstance!

Best,
Erika
 
E
exhibits-feedback <exhibits-feedback-bounces@lists.stanford.edu>
 on behalf of 
Catherine A. Aster
   |
Yesterday, 1:26 PM
 ATT00001.txt
492 bytes

Download  Save to OneDrive - Leland Stanford Junior University
Hi Erika,

I know Amy Hodge will follow up with you tomorrow (I am out of town & just happened to see your message). I am mystified, because I was able to create (and then I deleted) a new test feature page, and a new about page on your exhibit, without experiencing the error you describe. On the off chance the server experienced a momentary outage, can I ask you to please try again?

Many thanks,
Cathy

Cathy Aster
Services Manager
Spotlight at Stanford
Electronic Theses & Dissertations
Map Projects
https://library.stanford.edu/people/caster

**Comment by amyehodge** [comment] 2017-10-23 15:43
Hi Ben,

I am attempting to verify what issues she is still having. 

I have verified that the home page is currently not editable -- still gives the error message "We're sorry, but something went wrong."

She is attempting to put together a skeleton version of a site for this project that she wants to show to the entire project team at a big meeting in Santa Cruz later this week (I will get the exact date). She's hoping to convince them that Spotlight would be an excellent way to showcase their work. So, it's important that we try to get this working for her so she can get this completed on time.

I do believe the issue with pages not being saved has been resolved (the names too long thing).

Is there a browser/OS combo that is preferred that I can suggest to her? I did the training with her very recently and feel that she has the technology well in hand. 

Thanks.
Amy

**Comment by blalbrit** [comment] 2017-10-23 15:51
For those following this ticket - the Homepage error is: https://app.honeybadger.io/projects/49092/faults/35145381#notice-summary

**Comment by blalbrit** [comment] 2017-10-23 16:03
analysis ticket #789

**Comment by camillevilla** [comment] 2017-10-23 16:56
I posted these in #789 as well, but wanted to provide some more screenshots for folks following the user-facing issue:

I've found some fishy things by poking around the Alcoa exhibit in prod. 

## Data leaking into the about pages / sir trevor interface is gone
This bug isn't reproducible 100% of the time, but seems to pop up after I try to edit the home page. 

<img width="984" alt="curation_-_edit_page___alcoa__research_and_context_-_spotlight_at_stanford_and_dlss" src="https://user-images.githubusercontent.com/5402927/31901621-cf2f0700-b7d6-11e7-9698-c159de7bcee2.png">

## Existing data is not available for editing

<img width="981" alt="curation_-_edit_page___alcoa__research_and_context_-_spotlight_at_stanford" src="https://user-images.githubusercontent.com/5402927/31901811-7078eda6-b7d7-11e7-8939-34fdfff9f115.png">

**Comment by amyehodge** [comment] 2017-10-23 16:59
Here is an update from the exhibit curator on her issues. Note that her presentation is THIS THURSDAY. I am going to see if I can help her with #3, as that doesn't seem like a bug at the moment.

"Thank you for checking in. I understand the team has many priority tasks, and I think if I can just get the Home page and 1-2 about pages complete, then I would be good to go for Thursday, 10/26.

As of now, I am having 3 issues:
1) The inability to add components to About pages. Here is what I see when I try to add:
 
![issue1](https://user-images.githubusercontent.com/5558511/31902155-b35585fc-b7d8-11e7-8503-6977436a7eae.png)

2) Inability to edit the Home Page. When I click "Edit", I see this:
![issue2](https://user-images.githubusercontent.com/5558511/31902162-b87d1586-b7d8-11e7-93e9-b9c1fac84062.png)

3) When I am able to add widget components, I am unclear as to how to format so that images are on the left, text on the right. For example, a "People" page that shows images of our consortium members with a brief description of their titles and research foci to the right. Similar to your Data Stories pages in the Research at Stanford Exhibit (which has been an incredibly helpful resource by the way, for crosschecking)

Any help would be amazing. Thank you so much for your responsiveness and help with troubleshooting."

**Comment by camillevilla** [comment] 2017-10-23 18:37
@amyehodge has the curator edited About pages and encountered the 1st bug I posted? (e.g. `{"data":[{"type":"image","data":` showing up in a textarea). Similar issues have occurred in Spotlight, and it looks like a short-term manual fix involves removing these artifacts from the content. See the bottom of [this ticket](https://github.com/cul-it/exhibits-library-cornell-edu/issues/88).

I'm still trying to figure out what's happening when no widgets show up. 😥

**Comment by amyehodge** [comment] 2017-10-23 18:54
I don't know if she has, but I have.

**Comment by mejackreed** [comment] 2017-10-23 21:45
Ok so two issues here:

 1. The BrowseBlock issue investigated by @camillevilla 
 1. The Image type (should not have been enabled). Fixed upstream here: https://github.com/projectblacklight/spotlight/pull/1849

**Comment by camillevilla** [comment] 2017-10-24 18:48
@amyehodge good news! The Alcoa exhibit home page can be edited again. 
The bug is caused by adding a browse widget to the page without a browse category. The manual change to the data required us to manually change the data on the server. 

## Good
![screen shot 2017-10-24 at 11 43 40 am](https://user-images.githubusercontent.com/5402927/31961859-e79a84ec-b8b0-11e7-9ef1-09a68e70df37.png)

## Bad
![screen shot 2017-10-24 at 11 43 52 am](https://user-images.githubusercontent.com/5402927/31961858-e78794cc-b8b0-11e7-93a6-f6fe29d18bff.png)

We are working on upstream fixes to Spotlight to prevent this from happening in the future. 
See: https://github.com/projectblacklight/spotlight/pull/1850

**Comment by amyehodge** [comment] 2017-10-24 18:57
Very exciting. Confirmed I can now edit the home page. I'll let the user know and give her the info on how to prevent it from happening again. She'll be thrilled!

**Comment by camillevilla** [comment] 2017-10-25 17:11
@amyehodge are there any additional issues affecting the Alcoa exhibit curator? Otherwise, I'll close this ticket and split out the Sir Trevor widget issues (i.e. leaking data) into another ticket.

**Comment by mejackreed** [comment] 2017-10-25 21:01
@camillevilla I'm still not seeing the exhibit in the "Unpublished" column on the exhibits landing page. I wonder if this is a separate issue?

**Comment by blalbrit** [comment] 2017-10-25 21:02
@mejackreed - apparently that's because this exhibit has been published for several days. I think the "unpublished" list might be a red herring.

**Comment by mejackreed** [comment] 2017-10-25 21:18
Great news. Sorry for the kerfuffle

**Closed** 2017-10-27 15:43 UTC
Labels: bug, production, ready
