### ISSUE TITLE
UI bugs (seemingly) introduced by recent commits

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/exhibits#511] opened 2017-07-20 21:36 UTC
Several UI issues have been reported by users via the Feedback button in recent days. I've done a little troubleshooting and _think_ these issues were introduced by recent commits. Hopefully the developers involved in the relevant work can double-check what I found and see if there's a good way to fix these issues. 

* The "Save this search" modal appears very briefly but immediately closes (so currently curators cannot save searches/create new browse categories)
* Selecting the "more" link in facets does not display the modal with facet values that should be displayed
* The "Limit your search" toggle icon appears at all viewport sizes, rather than just at medium and below, when the facets collapse
* The SUL styling for `btn-primary` has changed from the cardinal red to the default Bootstrap blue 

I went back to previous versions of master to try to understand when the issues cropped up:

db72d33 - None of the issues above are evident. All appears fine:

![all-okay-db72d33](https://user-images.githubusercontent.com/101482/28439706-dd007d42-6d57-11e7-912c-0d9977b87046.png)

d295c87 - The Save this search modal works normally, but the unwanted toggle icon appears and the `btn-primary` color incorrectly blue. This was the "Add mirador_rails gem" commit on 5/9 (but not merged until July 5):

![icon-colors-problem-d295c87](https://user-images.githubusercontent.com/101482/28439704-d3c3c70c-6d57-11e7-8c5d-a41affbbf047.png)

4efd5ec - All problems we currently see occur starting with this commit. This was the "Reorder js to prevent problem with spotlight JS" commit on 5/25 (but also not merged until July 5).

**Comment by jkeck** [comment] 2017-07-24 16:45
I wonder if the mirador javascript is loading a version of a dependency that is conflicting w/ a javascript library that we also depend on?

**Comment by csbailey5t** [comment] 2017-07-27 18:08
The styling issues seem to be caused by the inclusion in `mirador-combined.css` of Bootstrap 3.3.7, among other vendor css. See https://github.com/sul-dlss/mirador_rails/blob/master/vendor/assets/stylesheets/mirador-combined.css. This is a css file coming from the mirador-rails gem. This is causing the color changes on buttons and the appearance of the toggle icon at all widths. It can be somewhat hackily fixed by moving `@import 'mirador-combined';` to the top of the `application.scss` file in Exhibits. That way, the bootstrap selectors in `mirador-combined` are overwritten by the bootstrap selectors and custom styles imported later.

This does have some side-effects. The text in some of the Mirador instance will be cardinal, though that may be acceptable. In general, the Mirador viewer instance seems to look fine otherwise, but may need a deeper look. 

Long term, the mirador_rails gem may need to rethink how it organizes its css, but this is complicated by Mirador's own large number of dependencies and dependence on styles from vendor libraries. While Mirador does namespace it's custom styling (in `less` files), it still uses styles from vendors, which are not namespaced.  It would be nice to not include bootstrap and such in the vendor css, but may be necessary for use of the gem in applications that don't otherwise include bootstrap.

**Comment by csbailey5t** [comment] 2017-07-27 18:36
Similarly, on the JS side, the `mirador.js.erb` file in the mirador_rails gem includes multiple vendor js libraries, including Bootstrap 3.3.7 (with modals, transitions, etc...), jQuery UI (which has its own references to modals), and Bootbox (which is a modal library used in Mirador around annotations if I remember correctly). Undoubtedly, one of these is the culprit for the clashing js that causes the Exhibits modals (such as Save this search) to close immediately without throwing any js errors in the console. 

There doesn't seem to be an easy fix for this. If you move the mirador include in `application.js` to the top, you fix the closing modal issue, and completely break Mirador. Moving it to the bottom creates a number of js errors in the console and causes Mirador to fail. 

Placing the include between `//= require blacklight/blacklight` and `//= require_tree .` will allow Mirador and the Save this search modal to work, but introduces a somewhat perplexing js error in the console: ```Uncaught TypeError: $(...).bl_checkbox_submit is not a function
    at catalog_edit.self-9a0906e….js?body=1:35
    at Object.activate (spotlight.self-50aeb93….js?body=1:10)
    at spotlight.self-50aeb93….js?body=1:17
    at Object.activate (core.self-e031fb8….js?body=1:10)
    at HTMLDocument.<anonymous> (core.self-e031fb8….js?body=1:36)
    at HTMLDocument.dispatch (jquery.self-bd7ddd3….js?body=1:5227)
    at HTMLDocument.elemData.handle (jquery.self-bd7ddd3….js?body=1:4879)
    at Object.t.dispatch (turbolinks.self-c5acd7a….js?body=1:6)
    at r.t.Controller.r.notifyApplicationAfterPageLoad (turbolinks.self-c5acd7a….js?body=1:6)
    at r.t.Controller.r.visitCompleted (turbolinks.self-c5acd7a….js?body=1:7)```

This error was the cause for the re-ordering of the of the js includes in the `application.js` file. The best course forward may be to dig deeper into this error, which seems to be an issue with a line from the Spotlight js: https://github.com/projectblacklight/spotlight/blob/master/app/assets/javascripts/spotlight/catalog_edit.js#L35

In the long-run, it may be necessary to figure out a way to build the mirador_rails gem that allows for optional includes of vendor libraries, both for js and css.

**Comment by jkeck** [comment] 2017-07-27 18:47
One thought I brought up when chatting about this w/ @csbailey5t is that we could not load the mirador assets via the asset pipeline (already kind of a bummer that every page has to load Mirador, even for exhibits that don't use the Mirador viewer).

Could we just load Mirador assets when we're rendering the Mirador viewer?  This might be a little hokey too, but would have the benefit of reducing the page weight for non-mirador pages as well as limits the scope that clashing assets will affect.

**Closed** 2017-08-03 15:47 UTC
Labels: bug, in progress
