### ISSUE TITLE
Date range facet - preliminary support

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/exhibits#971] opened 2017-12-02 01:26 UTC
As an exhibit creator or exhibit user, I should be able to facet based upon a range of dates at the year level.

**Comment by cbeer** [comment] 2017-12-02 03:05
Duplicate of #548?

**Comment by anarchivist** [comment] 2017-12-02 22:06
I'll take a closer look but I'd guess so. Thanks!

**Comment by anarchivist** [comment] 2017-12-04 19:30
I'm not sure this is a full duplicate - this doesn't presume that the dates are encoded as a range themselves. I'd be inclined to split that part of #548 out here.

**Closed** 2017-12-12 07:16 UTC
Labels: enhancement, in progress, virtualtribunals
