### ISSUE TITLE
Error preventing page from being saved: "Posters" browse category thumbnail for Stanford Stories exhibit

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#1874] opened 2020-05-04 20:24 UTC
I am trying to make incremental improvements to numerous University Archives exhibits. In this exhibit: https://exhibits.stanford.edu/stanford-stories/searches/posters I am trying to change the thumbnail for the browse category "Posters" and I keep seeing a message which is not accurate:

![Screen Shot 2020-05-04 at 1 21 23 PM](https://user-images.githubusercontent.com/3210225/81010078-9347e100-8e0a-11ea-9061-b2683560b29a.png)

**Comment by caaster** [comment] 2020-05-04 21:37
I'm adding another problem here which seems like it could possibly be related. For the Computer Science @ Stanford exhibit, two Browse category thumbnails seem broken. I can't upload or select a different image from the collection to fix the problem.

https://exhibits.stanford.edu/cs/searches/john-hennessy

https://exhibits.stanford.edu/cs/browse/daphne-koller

**Comment by jkeck** [comment] 2020-05-21 21:49
@caaster can you provide more details about what image you're trying to update the thumbnail to in the Posters exhibit?

WRT the other two issues, they are the same as each other at least.
The Daphne Koller exhibit is using zb772gz3468 for the thumbnail
The John Hennessy exhibit is using tx044bv9548 for the thumbnail

In both of these cases, the image-server is throwing an error when trying to load the image.  The error is typically caused by a bad JP2 image.  (From what I hear, this may be addressed by openjpeg).  If you would like, I can manually clear the thumbnail for both of those exhibits which should allow them to be changed in the interim.

**Comment by caaster** [comment] 2020-05-21 23:12
@jkeck - for: https://exhibits.stanford.edu/stanford-stories/searches/posters -- I am simply trying to re-crop a sloppy-looking crop of the existing image being used as the browse category thumbnail

**Comment by caaster** [comment] 2020-05-21 23:13
@jkeck for the other two issues, yes -- please manually clear the thumbnails if you could -- does this mean, though -- that if I try and re-use these images I will get the same type of error? and I should use different images?

**Comment by jkeck** [comment] 2020-05-22 15:44
Correct, you will not be able to use those particular images because the image server is currently unable to present the thumbnail "crop" for us.

I've manually removed the thumbnails from those two exhibits, so new thumbnails can be applied now.

**Comment by jkeck** [comment] 2020-05-22 15:49
I also filed projectblacklight/spotlight#2537 which would hopefully allow for curators/admins to still switch out thumbs/mastheads in the case where the IIIF endpoint no longer response successfully.

**Comment by jkeck** [comment] 2020-05-22 16:41
That is a completely separate issue that has not yet been resolved.

**Comment by jkeck** [comment] 2020-05-22 22:32
Okay, my theory here is that an image was uploaded (which happens to be the Gaieties poster) that was at or over the 10mb limit before we put that limit in place.  Now, that is causing a validation error when trying to save.

I've gone ahead and removed the reference to the uploaded version of the Gaieties poster as a thumbnail and applied the document's version as the thumb.  I've also taken a rough crop similar to what was there before (just to ensure it would apply and save).  You should be good to edit this thumbnail as needed now.

I'll close this issue, as I think all the reported problems have been resolved (and follow on tasks ticketed elsewhere).  Please feel free to re-open if this crops back of up for Posters.

**Closed by jkeck** 2020-05-22 22:32 UTC
Labels: bug
