### ISSUE TITLE
Ability to sort collection facet from A-Z is not working

### ISSUE THREAD

**Issue by caaster** [sul-dlss/exhibits#2010] opened 2021-03-01 17:56 UTC
Reported by library staff today for https://exhibits.stanford.edu/black-at-stanford. The ability to sort A-Z in the collection facet for this exhibit is not working.

![Screen Shot 2021-03-01 at 9 54 32 AM](https://user-images.githubusercontent.com/3210225/109537963-66894800-7a74-11eb-8237-f4aa2514c60a.png)

**Comment by caaster** [comment] 2021-03-01 18:01
This appears to just be affecting the A-Z sort on the collection facet. Here is another example, for: https://exhibits.stanford.edu/activism

![Screen Shot 2021-03-01 at 10 00 49 AM](https://user-images.githubusercontent.com/3210225/109538514-08109980-7a75-11eb-8973-7d82858326d7.png)

**Comment by cbeer** [comment] 2021-03-01 18:04
Duplicate of #810?

**Comment by anarchivist** [comment] 2022-04-15 16:18
Closing as duplicate.

**Closed by anarchivist** 2022-04-15 16:18 UTC
Labels: bug
