### ISSUE TITLE
Prev / Next buttons on homepage have lost styling

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/exhibits#1707] opened 2020-02-18 23:41 UTC
<img width="306" alt="Screen Shot 2020-02-18 at 3 40 01 PM" src="https://user-images.githubusercontent.com/5402927/74787860-107ca480-5265-11ea-8b92-a6ebc73e0a21.png">

**Comment by cbeer** [comment] 2020-02-18 23:44
Duplicate of #1701, just waiting for a new spotlight release.

**Closed by cbeer** 2020-02-18 23:44 UTC
